### ISSUE TITLE
Alternative means of payment (Bitcoin, PayPal...)

### ISSUE THREAD

**Issue by secsavvyX** [skerkour/black-hat-rust#10]
hello, can i buy this book with bitcoin ?
if yes how can i contact you ?

**Comment by skerkour** [comment]
Hello,
Thank you very much for your interest!

Unfortunately, while the book is still work in progress, I can only accept payments via [Stripe](https://stripe.com) for accounting reasons and to have an unified base of clients to send the updates.

That being said, once the book is complete, I will investigate how to provide other means of payment, so I will keep this issue open for people interest to +1

Kind regards,
Sylvain

**Comment by skerkour** [comment]
Thank you for the suggestion @adoerr !

As this is definitely a recurring question. I will for sure do my best to provide other means of payment once the book is completed (circa end of September), and I will publish updates here.

Just to better understand the desire I will post different means of payment. Please upvote your favorite one or comment if it's missing.

**Comment by skerkour** [comment]
Amazon

**Comment by skerkour** [comment]
Paypal

**Comment by skerkour** [comment]
BTC

**Comment by skerkour** [comment]
wechat

**Comment by skerkour** [comment]
Alipay

**Comment by GitLauza** [comment]
On this note I just want to say that I tried to buy the book as a x-mas gift to my brother. But the Stripe payment didn't work. After providing the credit card number I was wrongly asked to correct my location, then returned to previous step an  once again asked for the credit card number. I was stuck. When looking in the DevTools console I saw that several requests been blocked due to CORS violations. So I started to get a bit suspicious. Was this maybe a live example of a chapter 9 exercise? Was I getting fooled. 

Am I? 

Would lave to see PayPal as an alternativ payment method soon so that I can buy (what seems to ve a very interesting book) to my brother.

Kind regards,
Laurence

**Comment by skerkour** [comment]
Dear @GitLauza ,
Thank you very much for your interest!

I'm sorry for the bad experience! Be assured that you have not been fooled and this is indeed a technical error.

Could you please send me an email (https://kerkour.com/about/) with more details such as your web browser, and your country, so I can froward the issue to [Podia](https://www.podia.com/)'s team (the platform I'm using the handle payments) and help them fix it.

Regarding PayPal payments, It has been a week that I've been waiting for my [Paddle](https://paddle.com/) account to be validated... It seems to be the only payment provider which has VAT invoicing bundled with PayPal. I've sent many messages to them to accelerate the procedure, I hope they are taking it seriously.

I'll publish any updates here.

Sorry again for the bad experience :/

Sylvain

**Comment by adoerr** [comment]
> Regarding PayPal payments, It has been a week that I've been waiting for my [Paddle](https://paddle.com/) account to be validated... It seems to be the only payment provider which has VAT invoicing bundled with PayPal. I've sent many messages to them to accelerate the procedure, I hope they are taking it seriously.
> 
> I'll publish any updates here.

So, this means that a PayPal payment option is in the works? Awesome!

**Comment by skerkour** [comment]
Hello everyone,
I've very good news: PayPal, Apple Pay and Google Pay payments are now available thanks to [Paddle](https://paddle.com) 🎉 

Go here to buy Black Hat Rust with these payment methods: https://kerkour.com/black-hat-rust/

🔔 Because it took time for the PayPayl integration to work, I’ve reactivated the coupon **BLACK-HAT-WEEK** for 1 week, until Friday, December 31 at 11:59 PM 🔔

Enter it when you are asked to pay:
<img width="492" alt="bhr_coupon" src="https://user-images.githubusercontent.com/6172808/147126667-7ccfe5e7-d894-46b9-87e7-f87eeb7d36c0.png">


Happy end of the year 🥳

**Comment by GitLauza** [comment]
Hello @skerkour!
Thank you for your swift response and I’m glad that there’s now alternative payment options. So now I’ll definately get the book for my brother. 

Unfortunately I don’t have any saved records or logs from my previouse experience. But if I run into problems again I’ll try to save some records and provide it to you. 

Happy hollidays!

Regards,
Laurence

**Comment by skerkour** [comment]
As cards, PayPal, Apple Pay, Google Pay and Alipay are now accepted, I'm going to close this issue.

Please send me a message (https://kerkour.com/about/) if for any reasons you can't use these methods of payment.
